# Generated by Django 4.2.8 on 2024-05-07 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('cognome', models.CharField(max_length=20)),
                ('annoNascita', models.CharField(max_length=4)),
                ('annoMorte', models.CharField(max_length=4)),
                ('biografia', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Museo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('citta', models.CharField(max_length=20)),
                ('stato', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Opera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeOp', models.CharField(max_length=50)),
                ('anno', models.CharField(max_length=4)),
                ('tipo', models.CharField(max_length=10)),
                ('materiale', models.CharField(max_length=30)),
                ('autore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opere', to='musei.autore')),
            ],
        ),
    ]
