# Generated by Django 4.2.8 on 2024-05-07 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musei', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opera',
            name='museo',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, related_name='opere', to='musei.museo'),
            preserve_default=False,
        ),
    ]
