# Generated by Django 4.2.8 on 2024-05-14 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musei', '0003_alter_autore_options_alter_museo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opera',
            name='img',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
